### ISSUE TITLE
GPIO - “ No access to /dev/mem. Try running as root!”

### ISSUE THREAD

**Issue by ykri** [fredrikbaberg/hassio-addons#105]
Hi Fredrik and thanks for your amazing Addon that let us use only one rpi for both HA and Octoprint.
 
I tried to install OctoPrint-Enclosure plugin. 
After giving me some build errors for missing gcc and python-dev (if I remember well), I used Portainer Addon in Hassio and Installed them with “apk add”. 
The build completed successfully and I can run the plugin but when I press the button that I defined to control a GPIO output its state does not change. 
In log I get the error:

 “ No access to /dev/mem. Try running as root!”

/dev/mem is not present in the octoprint container console in Portainer but I am not a docker expert to understand visibility of devices in a docker environment. 

Thanks

**Comment by fredrikbaberg** [comment]
Without looking too much into the plugin, I assume it needs access to GPIO? If so, it will probably fail since I have not added that permission. In `config.json` it could be enough to add `"gpio": true`. It could also be the case that a modification is needed to AppArmor. I don´t have a custom AppArmor profile, so I hope not.

I'll have to look at it later, not sure when right now. If you are OK with experimenting you could try to override the config:

- Create backup of OctoPrint addon
- In folder addon, create a folder e.g. `octoprint_test` with the following file: https://github.com/fredrikbaberg/hassio-addons/blob/master/octoprint/config.json
  - Add line `"gpio": true"` to the file
- Install/start addon, which should now be visible from Supervisor

This will share the config/octoprint folder, but probably has its own persistent storage (I haven't checked). In addon configuration, if you set "add_build_packages: true" you should have both gcc and python-dev after restart.

I'm not sure if it is possible to modify `config.json` some other way, if there is a way to modify it for the already installed addon that would make it easier to test.

Reference to config: https://developers.home-assistant.io/docs/add-ons/configuration

**Comment by ykri** [comment]
Thanks, I'll try it!

**Comment by ykri** [comment]
- As you suggested, I added `"gpio":  true `in a new `config.json` in  `addons/octoprint_test/` and it mapped alright `/sys/class/gpio/`.Unfortunately OctoPrint-Enclosure plugin requires access to `/dev/mem/` because I get 
``
octoprint.plugins.enclosure - WARNING - An exception of type RuntimeError occurred on log_error. Arguments:
('No access to /dev/mem.  Try running as root!',)
``

- I then tried to add `"devices": ["/dev/mem:/dev/mem:rwm"]` in `config.json`. Again no luck. /dev/mem does not map in octoprint container. Unless I have the syntax wrong, the solution is elsewhere.

**Comment by fredrikbaberg** [comment]
I've had a look at it now, I think a custom AppArmor profile is needed for this to work properly. I'll have to read how that works, which will not be this month.
If you are not at all concerned with security (not recommended), you could disable AppArmor for the addon.  See the last lines of this Gist: https://gist.github.com/fredrikbaberg/0227af93a5382bde277bc663394f6de9

**Comment by ykri** [comment]
It's alright Fredrik, I have found a workaround for the moment. I use HA to control the GPIO output I needed.

**Comment by fredrikbaberg** [comment]
GPIO works with addon "OctoPrint Next", as long as the same GPIO is not also configured in HA.

Closing this issue.
