### ISSUE TITLE
Octoprint-Octolapse require writes in /dev/sg* devices

### ISSUE THREAD

**Issue by joskfg** [fredrikbaberg/hassio-addons#174]
Currently the devices are mounter just in RO mode, this avoids me to use a DSLR camera to do lapses with octolapse because octolapse tries to write to the a SCSI device (like /dev/sg0).

Is it possible to enable access to it?

By another hand, this requires gphoto2 to be installed and I do it manually, but it could be awesome to have it preinstalled in the docker image.

What do you think is the best approach to achieve Octolapse + DSRL camera within this addon?

**Comment by joskfg** [comment]
I'm using the octoprint addon

**Comment by joskfg** [comment]
I fixed it in my local copying you addon and modifying

**apparmor.txt** to allow /dev/sg0 together with /dev/gpiomem that was already there.
**config.json** adding de /dev/sg0 to the devices key.

**Comment by fredrikbaberg** [comment]
I haven't considered using a DSLR so haven't investigated this. I do have a compact camera that seems compatible with gphoto2, so I should be able to test it later.

Where there any specific instructions you used to setup Octolapse with gphoto2, so I can test it?

I assume you added gphoto2 through modifying the Dockerfile? I'll see if I can add it to the next update of the addon, depending on the required additional size, but it may take some time as I encountered an issue that prevents me from updating.

Is `/dev/sg0` always the correct path? When I first created this addon there were some issues with different paths, which was later fixed by adding `usb` and `uart` option to avoid mapping specific devices.

**Comment by joskfg** [comment]
In my case, It is always the same.  I did it in a dirty way accessing to the container directly and doing the changes manually. 

By the other hand I enables the SG driver in the has sido kernel. 
```
modprobe SG
```

**Comment by fredrikbaberg** [comment]
I'll at least make sure gphoto2 is available when I get to work on a new update.

I should get access to a DSLR in a week or two (Nikon D40, old but seems compatible). I'll try to locate a compatible compact camera as well. That should make it possible for me to do some testing.

**Comment by fredrikbaberg** [comment]
I finally found my other camera so I should be able to see how it works with both a Nikon D40 and a Nikon Coolpix S3700 this week
