### ISSUE TITLE
Octoprint Standard

### ISSUE THREAD

**Issue by DougJunior** [fredrikbaberg/hassio-addons#20]
Hi,

trying to use the normal octoprint installation, problem is that there is no permision to use the 3d printer and with a camera would be the same issue.

Connecting to: /dev/ttyUSB0Changing monitoring state from "Offline" to "Error: Connection error, see Terminal tab"Unexpected error while connecting to serial port: /dev/ttyUSB0 SerialException: '[Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'' @ comm.py:_openSerial:2308 (hook default)

**Comment by fredrikbaberg** [comment]
I haven't tried this with a camera (one reason is I don't have one to try with).
Not sure why the addon does not work, I haven't had the time to debug it yet. Printer has been offline for a few months.

**Comment by DougJunior** [comment]
WHen i understand the changes from homeassistent correct, you need to give the container on startup what typ of device you want to use with it.
https://developers.home-assistant.io/docs/en/hassio_addon_config.html
devices -->  Device list to map into the add-on. Format is: <path_on_host>:<path_in_container>:<cgroup_permissions>. i.e. /dev/ttyAMA0:/dev/ttyAMA0:rwm

i have seen this in another addon, but i can not find it. I hope this helpes.

**Comment by fredrikbaberg** [comment]
I have auto_uart instead of mapping specific devices, since not all printers map to the same device. So I don't think that's the issue.

In the branch fix_hassio I've started to update the files, but I need to go back to virtualenv in order to have persistent plugins (the one I tried was installed using pip, and not stored to /data, so it was lost on restart).

**Comment by fredrikbaberg** [comment]
@DougJunior I've just added Octoprint Dev, which should (soon) be possible to install without building locally. Could you see if that works? It's available for `amd64` and `i386` platform so far (waiting for script to complete).

Also, I remembered why I had things under `/config` instead of `/data`, addons will most likely be cleared on update and reinstall. But since I don't update this very often that might be OK, instead of having 100+ MB of files in `/config` for backup.

**Comment by DougJunior** [comment]
First Test, i deletet all files from the config directory, and loaded the dev build.
Setting up worked ok.
Autofinding the printer dosend worked, after selecting the port manual it connected smoothly.
I current trying printing a file that is allready on the sd card.
tomorrow i test more.

**Comment by DougJunior** [comment]
HI, testet the octoprint def with diffrent gcode files, from the octoprint and the printer it self, managet to get a 9hour print well done without issues. The camera i need to search next week that i can give you for this a report back. Thx for fixing this problems
