### ISSUE TITLE
[OctoPrint Next Dev] Klipper isn't starting

### ISSUE THREAD

**Issue by bruvv** [fredrikbaberg/hassio-addons#209]
As I am just new to klipper I wanted to use it but it is not starting in the octoprint gui. I logged into the container and tried to see where it was possibly failing.  When following the dockerfile:
```
    cd /data/klipper && \
    make clean && make && \
    ./scripts/flash-linux.sh && \
```
It errors at `make` with:
```
make: arm-none-eabi-gcc: No such file or directory
make: *** [Makefile:64: out/src/sched.o] Error 127
```
When setting it myself this is because klipper isn't installed yet. I tried running `./data/klipper/scripts/install-debian.sh` but that doesn't work. And I cannot find a way to add that `sched.o` build file. When performing the same steps on my kali linux setup it works fine. Also with this build it works fine: https://github.com/fredrikbaberg/hassio-addons/blob/master/octoprint-klipper/Dockerfile

**Comment by fredrikbaberg** [comment]
I've just gotten a Raspberry Pi 3B setup for testing. I'm currently using FluiddPi after my SD card gave up some months ago, so I haven't tested this version with actual hardware. Before that I was using `octoprint-klipper`, which worked fine for me.

How did you attempt to start it, "Start Klipper" from the menu? Did you also install the OctoKlipper plugin? I don't know how far you've gotten with Klipper yet, a change of firmware is usually required, but it should be possible to get at least to the point where Klipper complains about the printer config.
I don't intend to support building the firmware to flash to printer, as it requires some user input I don't think is available from the UI. The lines with `./scripts/flash-linux.sh` are instead for using a Raspberry Pi as a secondary MCU (https://www.klipper3d.org/RPi_microcontroller.html), which for me is useful for measuring resonances with a sensor (https://www.klipper3d.org/Measuring_Resonances.html). I have that setup on FluiddPi, but not sure if I can get it to work with the addon.

I think I saw the failure due to `arm-none-eabi-gcc` when I created the `octoprint-klipper` addon. I don't remember if it was a missing dependency.

Be aware that AppArmor blocks at least "Update Klipper from git", there could be other processes blocked because of that. I'll have to update the apparmor configuration.
