### ISSUE TITLE
Latest version breaks the addon

### ISSUE THREAD

**Issue by ful4n1t0c0sme** [fredrikbaberg/hassio-addons#290]
The latest version of Cotoprint ruins the addon. 
You install the addon. Then update octoprint. Then you no more are be able to login anymore.

**Comment by kingbob2** [comment]
same. I am no longer able to access the Octoprint UI from within HomeAssistant. I have turned on an external port so I can still log in to the octoprint instance as a work around for now.
Error shows Passive login failed. Octoprint log just shows "New connection from client:" then "Client closed connection:"

**Comment by fredrikbaberg** [comment]
I'll have a look at it, I should have a bit of time this weekend and parts of next week. At what version of OctoPrint did the issue start?
Sounds like OctoPrint either improved on security or introduced a bug (I'm guessing it's the first case and something with the proxy settings in the addon).

**Comment by ful4n1t0c0sme** [comment]
Update to 1.8.3 breaks everything.

**Comment by fredrikbaberg** [comment]
Thank you. I've confirmed the issue and am looking for a solution.
If necessary, it should be possible to downgrade to OctoPrint 1.8.2 for now through SSH (`pip install OctoPrint==1.8.2` after SSH into the addon). Not sure if it also is possible through the UI by using the external port.

**Comment by fredrikbaberg** [comment]
I'm still looking into this and have asked developers of both Home Assistant and OctoPrint for suggestions on how to proceed.
We've found some things that needs to be changed, but not enough to resolve this yet.

**Comment by ericreich** [comment]
Are there any updates to this?  I also had this issue and had to restore from backups.

**Comment by silycr** [comment]
Just updated to Octoprint 1.8.6. Direct login to the port works, however login through HomeAssistant does not.

**Comment by Carapijo** [comment]
> Thank you. I've confirmed the issue and am looking for a solution. If necessary, it should be possible to downgrade to OctoPrint 1.8.2 for now through SSH (`pip install OctoPrint==1.8.2` after SSH into the addon - HOWEVER I just noticed there was a change in how passwords are stored, so you may need to set a new password!). Not sure if it also is possible through the UI by using the external port.

Sorry, can you explain hoy to do SSH after the addon?
Thanks.

**Comment by fredrikbaberg** [comment]
> > Thank you. I've confirmed the issue and am looking for a solution. If necessary, it should be possible to downgrade to OctoPrint 1.8.2 for now through SSH (`pip install OctoPrint==1.8.2` after SSH into the addon - HOWEVER I just noticed there was a change in how passwords are stored, so you may need to set a new password!). Not sure if it also is possible through the UI by using the external port.
> 
> Sorry, can you explain how to do SSH into the addon? Thanks.

I use the addon "SSH & Web Terminal" for this, but you should also be able to use the [command line](https://www.home-assistant.io/common-tasks/os#home-assistant-via-the-command-line). The command should be something like: `docker exec -it addon_774437fd_3dprinter /bin/bash`. I believe it's the correct ID (774437fd_3dprinter), otherwise you can see the correct value on the addon settings page.

**Comment by Carapijo** [comment]
> docker exec -it addon_774437fd_3dprinter /bin/bash

Thank for helping, but i´m new in this and couldn´t update in SSH, maybe i´ll wait till yours

**Comment by piechade** [comment]
Nothing new about the fix?

**Comment by fredrikbaberg** [comment]
Sorry, no news. In total I've spent several days looking into this, without making any real progress.
I thought the issue was with CSRF but am not sure anymore as disabling it doesn't help. Since I can't seem to figure it out, unless there is someone else who can help, the main option I see right now is to disable Ingress completely. The alternative would be to add logic to revert to 1.8.2 and attempt to block upgrades, but I don't think that's a sustainable option.

The current guess is that the issue occurs somewhere between Ingress and the reverse proxy.

**Comment by fredrikbaberg** [comment]
I've published an update that should be able to revert to OctoPrint 1.7.3 where Ingress should work. Other than that, I can't do much more. This also means I won't add more updates to this add-on. I'm moving towards a new version, available at https://github.com/fredrikbaberg/ha-3dprinter-addons, but it also won't use Ingress.

**Comment by piechade** [comment]
That makes no sense, why you removed the hole Ingress because of the login issue? Can you build a version with Ingress and without auto login? You also removed the possibility to access octoprint over nabu casa cloud.

**Comment by fredrikbaberg** [comment]
> That makes no sense, why you removed the hole Ingress because of the login issue? Can you build a version with Ingress and without auto login? You also removed the possibility to access octoprint over nabu casa cloud with this decision.

To clarify: the latest update of "3DPrinter" does not remove Ingress from the add-on, it just adds an option to revert to OctoPrint 1.7.3 (there were some additional things I had to modify for the addon to work as the base image has been updated, such as changes to s6-Overlay). I don't intend to remove functionality for available add-ons unless it's required for security/safety (which this isn't, as far as I know). What I will do, though, is make it clear that the add-on will not be updated - through changing the _stage_ to deprecated and updating the description.

I am aware of the implications of this. I've been trying to find a solution for months, including discussions with developers of OctoPrint and asking for help. I haven't been able to work on any other issue because of this. I wouldn't have made the decision unless I thought it was necessary.
It's partially a case of managing expectations: If I see an add-on marked as _stable_ with _Ingress_ I will assume it works, not that I will need to avoid the update button for even the initial setup to work.

While not optimal, what can be done is to use a [plugin for remote access](https://plugins.octoprint.org/topics/remote_access/) I've quickly tried OctoEverywhere and Karmen with new add-on, but I would assume it to work with this. It's not nicely accessible from within Home Assistant, but it makes it possible to access OctoPrint remotely even without opening any ports. https://www.home-assistant.io/integrations/octoprint/ should still work, even without Ingress and plugin for remote access.

## The issue

During the time I've spent on trying to fix this, I haven't found that it is enough to disable auto login. There will still be a "CSRF validation failed" message when you attempt to login, it's just that you must enter your credentials and press the login button. On the other hand, I haven't found completely disabling CSRF to help, which is one of the reasons I have issues with debugging.
Let me know if you still want me to add an option to disable auto login, but note that there will also be changes required to the reverse proxy config. OctoPrint added a page (`/reverse_proxy_test`) to help with debugging issues with reverse proxy configration, I've gotten all clear on the other add-on (using another reverse proxy server) also without auto login, and still had the issue (at one point it worked the first time, but not after I closed the browser and tried again).

## Conclusions / TL; DR

* I'm not removing Ingress from the 3DPrinter addon in this repository, but I also don't plan to update this version anymore.
* I don't want to remove Ingress, but I can't have it included if it's broken - and it is broken for this add-on.
* The new add-on, in the other repository, will not have Ingress - unless someone finds a solution, in that case I'll happily add it.

### If you have ideas on how to make Ingress work, I'll happily accept PRs.
